version: '3.4'

services:
  # Funktioniert nicht, muss nochmal neu getestet werden
#  app:
#    build: .
#    container_name: "rezepteapp"
#    ports:
#      - 80:80
#    depends_on:
#      - postgres
  # postgres
  postgres:
    # mdillon/postgis is postgres + PostGIS (only). if you need additional
    # extensions, it's probably time to create a purpose-built image with all
    # necessary extensions. sorry, and thanks for adding support for them!
    image: "library/postgres:12.3"
    container_name: "postgres-database"
    volumes:
      # This is not in the local folder when using it, but provided to create backups
      - database-data:/var/lib/postgresql/data/
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "44444:5432"
    environment:
      POSTGRES_USER: "postgresqluser"
      POSTGRES_PASSWORD: ";*TcoAU6,-zrHLBh6-(MO/']e.-E`*7LV[;@&7Tb"
      POSTGRES_DB: "rezepte"
    restart: unless-stopped

volumes:
  database-data: